const $=id=>document.getElementById(id);
const money=n=>(Number(n)||0).toLocaleString('vi-VN')+' đ';
const plainMoney=n=>(Number(n)||0).toLocaleString('vi-VN');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const DOCS={quantity:'Bảng khối lượng',request:'Đề nghị thanh toán',receipt:'Phiếu thu',payment:'Phiếu chi'};
let schools=[...(window.BILLING_SCHOOLS_FALLBACK||[])],currentSchool=null,rows=[],rules=[],adjustments=[],currentDoc='quantity',version=1;
let lastBilling={tuition:0,service:0,adjust:0,final:0,commission:0};
let includedDocs={quantity:true,request:true,receipt:true,payment:true};
let docDrafts={};
const STORAGE='sunbot_billing_case_v22';
function isoToday(){return new Date().toISOString().slice(0,10)}
function currentMonth(){return new Date().toISOString().slice(0,7)}
function monthText(v){if(!v)return'';const [y,m]=v.split('-');return`Tháng ${m}/${y}`}
function vnDate(v){if(!v)return'';const d=new Date(v+'T00:00:00');return`Ngày ${String(d.getDate()).padStart(2,'0')} tháng ${String(d.getMonth()+1).padStart(2,'0')} năm ${d.getFullYear()}`}
function stamp(){const d=new Date();return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}_${String(d.getHours()).padStart(2,'0')}${String(d.getMinutes()).padStart(2,'0')}`}
function makeRules(s){return[
 {code:'FULL_MONTH',name:'Học đủ tháng',source:'full',tuition:+s.fullTuition||0,service:+s.fullService||0,note:'Mức thu chuẩn'},
 {code:'HALF_MONTH',name:'Học 1/2 tháng',source:'half_non_teacher',tuition:+s.halfTuition||Math.round((+s.fullTuition||0)/2),service:+s.fullService||0,note:'Áp dụng trẻ học không quá 1/2 kỳ theo quy định'},
 {code:'TEACHER_CHILD_HALF',name:'Con giáo viên học 1/2 tháng',source:'teacherHalf',tuition:+s.teacherHalfTuition||Math.round((+s.fullTuition||0)/4),service:+s.fullService||0,note:'Mức giảm riêng cho con giáo viên'}
]}
async function backend(action,payload={}){const url=window.BILLING_BACKEND_URL;if(!url)throw new Error('LOCAL');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const j=await r.json();if(!j.ok)throw new Error(j.message||'Backend lỗi');return j}
async function loadBackend(){if(!window.BILLING_BACKEND_URL){setBackend(false);renderSchoolOptions();return}try{const r=await backend('getBillingSchools');if(Array.isArray(r.schools)&&r.schools.length)schools=r.schools;setBackend(true)}catch(e){setBackend(false)}renderSchoolOptions()}
function setBackend(ok){$('backendDot').className='dot '+(ok?'ok':'local');$('backendText').textContent=ok?'Đã kết nối Google Sheet backend':'Đang dùng dữ liệu cục bộ'}
function renderSchoolOptions(){const sel=$('schoolSelect'),old=sel.value;sel.innerHTML='<option value="">-- Chọn trường --</option>'+schools.filter(s=>s.active!==false).map(s=>`<option value="${esc(s.code)}">${esc(s.name)}</option>`).join('');if(old&&schools.some(s=>s.code===old))sel.value=old}
function selectSchool(code){captureCurrentDoc();currentSchool=schools.find(s=>s.code===code)||null;docDrafts={};if(!currentSchool){$('caseSub').textContent='Chưa chọn trường';return}rules=makeRules(currentSchool);$('commissionPct').value=currentSchool.commission??20;$('serviceName').value=currentSchool.serviceName||'Chương trình Lập trình tư duy cùng Sunbot';$('showBank').checked=currentSchool.showBank!==false;renderRules();calculate();renderDocs()}
function goStep(n){captureCurrentDoc();document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));document.querySelectorAll('.panel').forEach((x,i)=>x.classList.toggle('active',i===n-1));if(n===4)renderDocs();if(n===5){renderChecklist();renderAllDocs();updateFilename()}}
function parseRaw(){const raw=$('rawInput').value.trim();if(!raw)return alert('Chưa có dữ liệu để chuyển.');const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out=[];for(const line of lines){if(/lớp.*sĩ số/i.test(line))continue;const p=line.includes('|')?line.split('|'):line.split('\t');if(p.length<5)continue;const vals=p.map(x=>x.trim()),nums=vals.slice(1,6).map(x=>Number(String(x).replace(/[^0-9.-]/g,''))||0);out.push({cls:vals[0],size:nums[0],full:nums[1],half:nums[2],absent:nums[3],teacherHalf:nums[4]||0,note:vals.slice(6).join(' | ')})}if(!out.length)return alert('Không nhận ra bảng. Hãy dùng định dạng có dấu | hoặc TSV như mẫu.');rows=out;docDrafts={};renderRows();validateRows();calculate();goStep(2)}
function demo(){if(!schools.some(s=>s.code==='MNB'))return;$('schoolSelect').value='MNB';selectSchool('MNB');$('billMonth').value='2026-08';rows=[
 {cls:'A1',size:21,full:21,half:0,absent:0,teacherHalf:0,note:'Phiếu ghi tổng 21 HS, trong đó có 1 con cô; chưa xác định chính sách giảm riêng.'},
 {cls:'A2',size:12,full:11,half:1,absent:0,teacherHalf:0,note:'Dương Minh Đăng học 1/2 tháng.'},
 {cls:'A3',size:1,full:1,half:0,absent:0,teacherHalf:0,note:'Phiếu ghi tổng 1 HS.'},
 {cls:'B1',size:13,full:13,half:0,absent:0,teacherHalf:0,note:'Phiếu ghi tổng 13 HS.'},
 {cls:'B2',size:17,full:17,half:0,absent:0,teacherHalf:0,note:'Phiếu ghi tổng 17 HS.'}
];docDrafts={};renderRows();validateRows();calculate();renderDocs()}
function addRow(r={cls:'',size:0,full:0,half:0,absent:0,teacherHalf:0,note:''}){rows.push(r);docDrafts={};renderRows()}
function renderRows(){$('quantityBody').innerHTML=rows.map((r,i)=>`<tr><td><input data-r="${i}" data-k="cls" value="${esc(r.cls)}"></td><td><input type="number" min="0" data-r="${i}" data-k="size" value="${r.size}"></td><td><input type="number" min="0" data-r="${i}" data-k="full" value="${r.full}"></td><td><input type="number" min="0" data-r="${i}" data-k="half" value="${r.half}"></td><td><input type="number" min="0" data-r="${i}" data-k="absent" value="${r.absent}"></td><td><input type="number" min="0" data-r="${i}" data-k="teacherHalf" value="${r.teacherHalf}"></td><td><input data-r="${i}" data-k="note" value="${esc(r.note)}"></td><td><button class="btn danger" data-delrow="${i}">Xóa</button></td></tr>`).join('');calculate()}
function validateRows(){const errs=[];rows.forEach((r,i)=>{if((+r.full)+(+r.half)+(+r.absent)!=(+r.size))errs.push(`${r.cls||'Dòng '+(i+1)}: sĩ số không cân.`);if((+r.teacherHalf)>(+r.half))errs.push(`${r.cls||'Dòng '+(i+1)}: con giáo viên vượt số trẻ học 1/2 tháng.`)});const b=$('validationBox');b.className='validation '+(errs.length?'bad':'ok');b.textContent=errs.length?errs.join(' '):'Dữ liệu hợp lệ: tất cả các lớp đã cân sĩ số.';return !errs.length}
function renderRules(){$('policyBody').innerHTML=rules.map((r,i)=>`<tr><td><input data-rule="${i}" data-k="name" value="${esc(r.name)}"></td><td><select data-rule="${i}" data-k="source"><option value="full" ${r.source==='full'?'selected':''}>Học đủ tháng</option><option value="half_non_teacher" ${r.source==='half_non_teacher'?'selected':''}>1/2 tháng, không gồm con GV</option><option value="teacherHalf" ${r.source==='teacherHalf'?'selected':''}>Con GV 1/2 tháng</option><option value="manual" ${r.source==='manual'?'selected':''}>Nhập tay</option></select>${r.source==='manual'?`<input type="number" min="0" data-rule="${i}" data-k="manualQty" value="${r.manualQty||0}">`:''}</td><td><input type="number" min="0" data-rule="${i}" data-k="tuition" value="${r.tuition||0}"></td><td><input type="number" min="0" data-rule="${i}" data-k="service" value="${r.service||0}"></td><td><button class="btn danger" data-delrule="${i}">Xóa</button></td></tr>`).join('')}
function renderAdjustments(){$('adjustBody').innerHTML=adjustments.map((a,i)=>`<tr><td><select data-adj="${i}" data-k="sign"><option value="-1" ${a.sign<0?'selected':''}>Giảm trừ</option><option value="1" ${a.sign>0?'selected':''}>Cộng / thưởng</option></select></td><td><input data-adj="${i}" data-k="text" value="${esc(a.text)}"></td><td><input type="number" min="0" data-adj="${i}" data-k="amount" value="${a.amount||0}"></td><td class="center"><input type="checkbox" data-adj="${i}" data-k="commission" ${a.commission?'checked':''}></td><td><button class="btn danger" data-deladj="${i}">Xóa</button></td></tr>`).join('')}
function qtyFor(rule){const t=rows.reduce((a,r)=>{a.full+=+r.full||0;a.half+=+r.half||0;a.teacher+=+r.teacherHalf||0;return a},{full:0,half:0,teacher:0});if(rule.source==='full')return t.full;if(rule.source==='half_non_teacher')return Math.max(0,t.half-t.teacher);if(rule.source==='teacherHalf')return t.teacher;return +rule.manualQty||0}
function calculate(){let tuition=0,service=0;for(const r of rules){const q=qtyFor(r);tuition+=q*(+r.tuition||0);service+=q*(+r.service||0)}const adj=adjustments.reduce((s,a)=>s+(+a.sign||-1)*(+a.amount||0),0),final=tuition+service+adj,mode=$('commissionMode').value;let base=mode==='final'?final:tuition+adjustments.filter(a=>a.commission).reduce((s,a)=>s+(+a.sign||-1)*(+a.amount||0),0);let commission=mode==='fixed'?(+$('commissionFixed').value||0):Math.round(base*((+$('commissionPct').value||0)/100));lastBilling={tuition,service,adjust:adj,final,commission};$('sumTuition').textContent=money(tuition);$('sumService').textContent=money(service);$('sumAdjust').textContent=(adj>=0?'+':'')+money(adj);$('sumFinal').textContent=money(final);$('sumCommission').textContent=money(commission);updateTitle();updateFilename()}
function updateTitle(){if(currentSchool)$('caseSub').textContent=`${currentSchool.name} · ${monthText($('billMonth').value)}`}
function refCode(type){const c=currentSchool?.code||'TRUONG',m=($('billMonth').value||'0000-00').replace('-','');return`SB-${type}-${c}-${m}-V${String(version).padStart(2,'0')}`}
function smartFilename(scope='BOSO'){const school=currentSchool?.code||'TRUONG',period=($('billMonth').value||'0000-00').replace('-','');return`Sunbot_${scope}_${school}_${period}_${stamp()}_v${String(version).padStart(2,'0')}.pdf`}
function editable(text,cls=''){return`<span class="editable ${cls}" contenteditable="true">${esc(text)}</span>`}
function companyHeader(national=true){return`<div class="doc-header"><div class="kiro-letterhead"><strong>${editable('CÔNG TY CỔ PHẦN CÔNG NGHỆ GIÁO DỤC KIRO VIỆT NAM')}</strong><br>${editable($('companyAddress').value)}<br>${editable('MST: 0108919688 · Hotline: 0866 109 086 · www.sunbot.vn')}</div>${national?`<div class="national-header"><strong>${editable('CỘNG HOÀ XÃ HỘI CHỦ NGHĨA VIỆT NAM')}</strong><span class="underline"><b>${editable('Độc lập - Tự do - Hạnh phúc')}</b></span></div>`:`<div class="logo-head"><img src="https://sunbotvietnam.github.io/quotation/assets/img/logo-sunbot.png" alt="Sunbot"></div>`}</div>`}
function footer(type){return`<div class="paper-footer"><span>Sunbot/Kiro · Hồ sơ thanh toán</span><span>${refCode(type)}</span></div>`}
function calcPolicyBlock(){const rowsHtml=rules.map(r=>{const total=(+r.tuition||0)+(+r.service||0);let note=r.note||'';if(r.code==='HALF_MONTH')note='Học 1/2 tháng; học phí bằng 50% mức học phí đủ tháng, dịch vụ bổ sung giữ theo cấu hình.';if(r.code==='TEACHER_CHILD_HALF')note='Mức thu riêng cho con giáo viên; học phí giảm theo chính sách của trường.';return`<tr><td>${editable(r.name)}</td><td class="num">${plainMoney(r.tuition)}</td><td class="num">${plainMoney(r.service)}</td><td class="num"><b>${plainMoney(total)}</b></td><td>${editable(note)}</td></tr>`}).join('');return`<div class="calc-box"><div class="calc-box-title">Căn cứ và cách tính</div><ul class="calc-list"><li>Đơn vị tính: Trẻ.</li><li>Thành tiền từng nhóm = Số trẻ thuộc nhóm × Mức thu của nhóm.</li><li>Tổng đề nghị thanh toán = Tổng học phí + Tổng dịch vụ bổ sung ± Các điều chỉnh/giảm trừ trong kỳ.</li></ul><table class="calc-policy"><thead><tr><th>Đối tượng</th><th>Học phí</th><th>DV bổ sung</th><th>Mức thu/trẻ</th><th>Ghi chú</th></tr></thead><tbody>${rowsHtml}</tbody></table></div>`}
function amountRow(r){let sum=0;for(const p of rules){let q=0;if(p.source==='full')q=+r.full||0;if(p.source==='half_non_teacher')q=Math.max(0,(+r.half||0)-(+r.teacherHalf||0));if(p.source==='teacherHalf')q=+r.teacherHalf||0;sum+=q*((+p.tuition||0)+(+p.service||0))}return sum}
function deleteControl(){return`<span class="doc-delete no-print" title="Xóa dòng khỏi chứng từ">×</span>`}
function quantityDoc(){const s=currentSchool||{name:'Chưa chọn trường',address:''};const body=rows.map((r,i)=>`<tr><td class="center">${deleteControl()}${i+1}</td><td>${editable(r.cls)}</td><td class="center">${editable(r.size)}</td><td class="center">${editable(r.full)}</td><td class="center">${editable(r.half)}</td><td class="center">${editable(r.absent)}</td><td class="num">${editable(plainMoney(amountRow(r)))}</td><td>${editable(r.note)}</td></tr>`).join('');return`<div class="paper"><div class="doc-body">${companyHeader(true)}<div class="doc-title"><h1>${editable('BẢNG XÁC ĐỊNH KHỐI LƯỢNG - SỐ LƯỢNG')}</h1><p><b>${editable(s.name)}</b> · <span class="month">${editable(monthText($('billMonth').value))}</span></p></div>${calcPolicyBlock()}<div class="meta-lines"><p><b>Địa chỉ:</b> ${editable(s.address||'')}</p></div><table class="print-table"><thead><tr><th style="width:5%">STT</th><th style="width:9%">Lớp</th><th style="width:8%">Sĩ số</th><th style="width:9%">Đủ tháng</th><th style="width:9%">1/2 tháng</th><th style="width:8%">Nghỉ</th><th style="width:16%">Thành tiền</th><th>Ghi chú chi tiết</th></tr></thead><tbody>${body}<tr class="total-row"><td colspan="6" class="center">TỔNG CỘNG</td><td class="num">${editable(plainMoney(lastBilling.final))}</td><td></td></tr></tbody></table><p class="doc-note"><b>Tổng số tiền cần thanh toán:</b> ${editable(money(lastBilling.final))}</p><p class="doc-note"><b>Bằng chữ:</b> <i>${editable(numberToWords(lastBilling.final))}</i></p><div class="signature"><div><strong>${editable('ĐẠI DIỆN NHÀ TRƯỜNG')}</strong><em>${editable('(Ký, đóng dấu)')}</em><div class="signature-space"></div></div><div><strong>${editable('ĐẠI DIỆN NHÀ CUNG CẤP')}</strong><em>${editable('(Ký, ghi rõ họ tên)')}</em><div class="signature-space"></div><b>${editable($('repName').value)}</b></div></div></div>${footer('KL')}</div>`}
function requestRows(){let stt=1;const fee=rules.map(r=>{const q=qtyFor(r);if(!q)return'';return`<tr><td class="center">${deleteControl()}${stt++}</td><td>${editable(r.name)}</td><td class="center">${editable(q)}</td><td class="center">Trẻ</td><td class="num">${editable(plainMoney((+r.tuition||0)+(+r.service||0)))}</td><td class="num">${editable(plainMoney(q*((+r.tuition||0)+(+r.service||0))))}</td></tr>`}).join('');let red='';if(adjustments.filter(a=>a.sign<0).length)red=adjustments.filter(a=>a.sign<0).map(a=>`<tr><td class="center">${deleteControl()}${stt++}</td><td>${editable(a.text||'Giảm trừ')}</td><td class="center">1</td><td class="center">Khoản</td><td class="num">-${editable(plainMoney(a.amount))}</td><td class="num">-${editable(plainMoney(a.amount))}</td></tr>`).join('');return{fee,red}}
function requestDoc(){const s=currentSchool||{name:'Chưa chọn trường',address:'',mst:''},rr=requestRows();const bank=$('showBank').checked?`<div class="doc-note"><p><b>5. Thông tin thanh toán:</b> Kính đề nghị Quý trường thanh toán bằng hình thức chuyển khoản:</p><p style="margin-left:18px">- <b>Người thụ hưởng:</b> ${editable('Công ty Cổ phần Công nghệ Giáo dục Kiro Việt Nam')}<br>- <b>Số tài khoản:</b> ${editable($('bankAccount').value)}<br>- <b>Ngân hàng:</b> ${editable($('bankName').value)}</p></div>`:'';return`<div class="paper"><div class="doc-body">${companyHeader(true)}<div class="doc-title"><h1>${editable('GIẤY ĐỀ NGHỊ THANH TOÁN')}</h1><p class="month">(${editable(monthText($('billMonth').value))})</p></div><div class="meta-lines"><p><b>Kính gửi:</b> ${editable(s.name)}</p><p><b>Địa chỉ:</b> ${editable(s.address||'')}</p>${s.mst?`<p><b>Mã số thuế:</b> ${editable(s.mst)}</p>`:''}<p><b>1. Đơn vị đề nghị thanh toán:</b> ${editable('Công ty CP Công nghệ giáo dục Kiro Việt Nam')}</p><p><b>2. Nội dung thanh toán:</b> ${editable(`Đề nghị trường thanh toán phí dịch vụ dạy học "${$('serviceName').value}" kỳ ${monthText($('billMonth').value)} theo quy định của hợp đồng.`)}</p></div>${calcPolicyBlock()}<p class="doc-note"><b>3. Bảng tổng hợp thanh toán:</b></p><table class="print-table"><thead><tr><th style="width:6%">STT</th><th>Khoản mục</th><th style="width:11%">Số lượng</th><th style="width:9%">ĐVT</th><th style="width:16%">Đơn giá/Mức</th><th style="width:19%">Thành tiền</th></tr></thead><tbody><tr class="section-row"><td class="center">I</td><td colspan="5">CÁC KHOẢN TÍNH PHÍ</td></tr>${rr.fee||'<tr><td>-</td><td colspan="5">Không phát sinh</td></tr>'}<tr class="section-row"><td class="center">II</td><td colspan="5">CÁC KHOẢN GIẢM TRỪ / ĐIỀU CHỈNH</td></tr>${rr.red||'<tr><td class="center">-</td><td colspan="5">Không phát sinh</td></tr>'}<tr class="total-row"><td colspan="5" class="center">TỔNG CỘNG ĐỀ NGHỊ THANH TOÁN</td><td class="num">${editable(plainMoney(lastBilling.final))}</td></tr></tbody></table><p class="doc-note"><b>Bằng chữ:</b> <i>${editable(numberToWords(lastBilling.final))}</i></p><p class="doc-note"><b>4. Chứng từ kèm theo:</b> ${editable(`Bảng xác định khối lượng - số lượng ${monthText($('billMonth').value)}.`)}</p>${bank}<div class="signature"><div><strong>${editable('ĐẠI DIỆN NHÀ TRƯỜNG')}</strong><em>${editable('(Ký, đóng dấu)')}</em><div class="signature-space"></div></div><div><div><i>${editable(vnDate($('docDate').value))}</i></div><strong>${editable('ĐẠI DIỆN NHÀ CUNG CẤP')}</strong><em>${editable('(Ký, ghi rõ họ tên)')}</em><div class="signature-space"></div><b>${editable($('repName').value)}</b></div></div></div>${footer('DNTT')}</div>`}
function cashDoc(isReceipt){const s=currentSchool||{name:'Chưa chọn trường',address:''},amount=isReceipt?lastBilling.final:lastBilling.commission,doc=isReceipt?'PHIẾU THU':'PHIẾU CHI',type=isReceipt?'THU':'CHI',action=isReceipt?'nộp':'nhận',reason=isReceipt?`Thanh toán học phí và dịch vụ chương trình Sunbot - ${monthText($('billMonth').value)}`:`Chi phí phối hợp quản lý vận hành chương trình Sunbot - ${monthText($('billMonth').value)}`;return`<div class="paper"><div class="doc-body">${companyHeader(false)}<div style="text-align:right;font-size:9pt"><b>${editable(isReceipt?'Mẫu số 01 - TT':'Mẫu số 02 - TT')}</b></div><div class="doc-title" style="margin-top:28px"><h1 style="font-size:18pt">${editable(doc)}</h1><p><i>${editable(vnDate($('docDate').value))}</i></p></div><table class="cash-lines"><tr><td>Đơn vị ${action} tiền:</td><td>${editable(s.name)}</td></tr><tr><td>Địa chỉ:</td><td>${editable(s.address||'')}</td></tr><tr><td>Lý do ${type.toLowerCase()}:</td><td>${editable(reason)}</td></tr><tr><td>Số tiền:</td><td><b>${editable(money(amount))}</b></td></tr><tr><td>Bằng chữ:</td><td class="money-words">${editable(numberToWords(amount))}</td></tr><tr><td>Kèm theo:</td><td>${editable('............................................................. chứng từ gốc.')}</td></tr></table><div class="signature" style="grid-template-columns:repeat(4,1fr);gap:8px;margin-top:28px"><div><strong>Kế toán</strong><div class="signature-space"></div></div><div><strong>Người lập phiếu</strong><div class="signature-space"></div></div><div><strong>${isReceipt?'Người nộp tiền':'Người nhận tiền'}</strong><div class="signature-space"></div></div><div><strong>Thủ quỹ</strong><div class="signature-space"></div></div></div></div>${footer(type)}</div>`}
function numberToWords(n){n=Math.round(Number(n)||0);if(!n)return'Không đồng';const d=['không','một','hai','ba','bốn','năm','sáu','bảy','tám','chín'];function read3(x,full){let tr=Math.floor(x/100),ch=Math.floor((x%100)/10),dv=x%10,s='';if(tr||full){s+=d[tr]+' trăm';if(!ch&&dv)s+=' lẻ '}if(ch>1){s+=d[ch]+' mươi';if(dv===1)s+=' mốt';else if(dv===5)s+=' lăm';else if(dv)s+=' '+d[dv]}else if(ch===1){s+='mười';if(dv===5)s+=' lăm';else if(dv)s+=' '+d[dv]}else if(dv&&!tr)s+=d[dv];return s.trim()}const units=['',' nghìn',' triệu',' tỷ',' nghìn tỷ',' triệu tỷ'];let parts=[],i=0;while(n>0){const g=n%1000;if(g)parts.unshift(read3(g,false)+units[i]);n=Math.floor(n/1000);i++}let out=parts.join(' ').replace(/\s+/g,' ').trim();return out.charAt(0).toUpperCase()+out.slice(1)+' đồng chẵn ./.'}
function generatedDoc(type){if(type==='quantity')return quantityDoc();if(type==='request')return requestDoc();if(type==='receipt')return cashDoc(true);return cashDoc(false)}
function captureCurrentDoc(){const p=$('docPreview');if(p&&p.firstElementChild&&currentDoc)docDrafts[currentDoc]=p.innerHTML}
function renderDocs(){document.querySelectorAll('.doc-btn').forEach(b=>{b.classList.toggle('active',b.dataset.doc===currentDoc);b.classList.toggle('excluded',!includedDocs[b.dataset.doc])});$('docPreview').innerHTML=docDrafts[currentDoc]||generatedDoc(currentDoc);bindDocEditor()}
function bindDocEditor(){const p=$('docPreview');p.querySelectorAll('.editable').forEach(el=>el.addEventListener('input',()=>{docDrafts[currentDoc]=p.innerHTML;$('caseStatus').textContent='ĐÃ CHỈNH TAY'}));p.querySelectorAll('.doc-delete').forEach(btn=>btn.addEventListener('click',()=>{btn.closest('tr')?.remove();docDrafts[currentDoc]=p.innerHTML;$('caseStatus').textContent='ĐÃ CHỈNH TAY'}))}
function regenerateCurrentDoc(){delete docDrafts[currentDoc];renderDocs();$('caseStatus').textContent='ĐANG SOẠN'}
function excludeCurrentDoc(){includedDocs[currentDoc]=false;renderDocs();renderChecklist();updateFilename()}
function renderChecklist(){$('docChecklist').innerHTML=Object.entries(DOCS).map(([k,v])=>`<label class="checkitem"><input type="checkbox" data-include-doc="${k}" ${includedDocs[k]?'checked':''}><span>${v}</span></label>`).join('')}
function renderAllDocs(){captureCurrentDoc();const html=Object.keys(DOCS).filter(k=>includedDocs[k]).map(k=>docDrafts[k]||generatedDoc(k)).join('');$('allDocsPreview').innerHTML=html}
function updateFilename(){if(!$('filenameBox'))return;$('filenameBox').textContent=smartFilename('BOSO')}
function collectCase(){captureCurrentDoc();return{schema:'SUNBOT_BILLING_V22',schoolCode:currentSchool?.code||'',month:$('billMonth').value,docDate:$('docDate').value,repName:$('repName').value,serviceName:$('serviceName').value,showBank:$('showBank').checked,companyAddress:$('companyAddress').value,bankAccount:$('bankAccount').value,bankName:$('bankName').value,rows,rules,adjustments,commissionMode:$('commissionMode').value,commissionPct:+$('commissionPct').value||0,commissionFixed:+$('commissionFixed').value||0,includedDocs,docDrafts,version}}
function restoreCase(c){if(!c)return;version=c.version||1;$('schoolSelect').value=c.schoolCode||'';currentSchool=schools.find(s=>s.code===c.schoolCode)||null;$('billMonth').value=c.month||currentMonth();$('docDate').value=c.docDate||isoToday();$('repName').value=c.repName||'';$('serviceName').value=c.serviceName||'Chương trình Lập trình tư duy cùng Sunbot';$('showBank').checked=c.showBank!==false;$('companyAddress').value=c.companyAddress||$('companyAddress').value;$('bankAccount').value=c.bankAccount||$('bankAccount').value;$('bankName').value=c.bankName||$('bankName').value;rows=Array.isArray(c.rows)?c.rows:[];rules=Array.isArray(c.rules)&&c.rules.length?c.rules:(currentSchool?makeRules(currentSchool):[]);adjustments=Array.isArray(c.adjustments)?c.adjustments:[];$('commissionMode').value=c.commissionMode||'net_tuition';$('commissionPct').value=c.commissionPct??20;$('commissionFixed').value=c.commissionFixed||0;includedDocs={quantity:true,request:true,receipt:true,payment:true,...(c.includedDocs||{})};docDrafts=c.docDrafts||{};renderRows();renderRules();renderAdjustments();calculate();renderDocs();renderChecklist();updateFilename()}
function saveCase(){const c=collectCase();version=(version||0)+1;c.version=version;localStorage.setItem(STORAGE,JSON.stringify(c));$('saveHint').textContent=`Đã lưu bản nháp v${String(version).padStart(2,'0')} lúc ${new Date().toLocaleTimeString('vi-VN')}.`;updateFilename();if(window.BILLING_BACKEND_URL)backend('saveBillingCase',{case:c}).catch(()=>{})}
function loadLastCase(){const raw=localStorage.getItem(STORAGE);if(!raw)return alert('Chưa có bản nháp cục bộ.');try{restoreCase(JSON.parse(raw))}catch(e){alert('Bản nháp không hợp lệ.') }}
function resetCase(){if(!confirm('Tạo hồ sơ mới? Dữ liệu chưa lưu sẽ mất.'))return;rows=[];adjustments=[];docDrafts={};includedDocs={quantity:true,request:true,receipt:true,payment:true};version=1;$('rawInput').value='';if(currentSchool)rules=makeRules(currentSchool);renderRows();renderRules();renderAdjustments();calculate();renderDocs();renderChecklist();$('caseStatus').textContent='ĐANG SOẠN'}
function exportBackup(){const blob=new Blob([JSON.stringify(collectCase(),null,2)],{type:'application/json;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=smartFilename('BACKUP').replace('.pdf','.json');a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importBackup(file){const fr=new FileReader();fr.onload=()=>{try{restoreCase(JSON.parse(fr.result))}catch(e){alert('Không đọc được file JSON.')}};fr.readAsText(file,'utf-8')}
function printAll(){if(!validateRows()&&!confirm('Dữ liệu khối lượng chưa hợp lệ. Vẫn tiếp tục xuất?'))return;captureCurrentDoc();renderAllDocs();document.querySelectorAll('.panel').forEach(x=>x.classList.remove('print-active'));$('panel5').classList.add('print-active');const old=document.title;document.title=smartFilename('BOSO').replace('.pdf','');setTimeout(()=>{window.print();setTimeout(()=>document.title=old,500)},100)}
function exportWord(){captureCurrentDoc();const html=docDrafts[currentDoc]||generatedDoc(currentDoc);const clean=document.createElement('div');clean.innerHTML=html;clean.querySelectorAll('.no-print,.doc-delete').forEach(x=>x.remove());clean.querySelectorAll('[contenteditable]').forEach(x=>x.removeAttribute('contenteditable'));const doc=`<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word'><head><meta charset='utf-8'><style>@page WordSection1{size:595.3pt 841.9pt;margin:42.5pt 56.7pt 42.5pt 56.7pt}div.WordSection1{page:WordSection1}body{font-family:'Times New Roman';font-size:11pt;line-height:1.28}table{width:100%;border-collapse:collapse}.print-table th,.print-table td,.calc-policy th,.calc-policy td{border:1px solid #000;padding:4px 5px;font-size:10pt}.paper-footer{margin-top:20px;border-top:1px solid #aaa;font-size:8pt}</style></head><body><div class='WordSection1'>${clean.innerHTML}</div></body></html>`;const blob=new Blob(['\ufeff',doc],{type:'application/msword'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=smartFilename(DOCS[currentDoc].toUpperCase().replaceAll(' ','_')).replace('.pdf','.doc');a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bind(){document.querySelectorAll('.step').forEach(b=>b.onclick=()=>goStep(+b.dataset.step));document.querySelectorAll('.doc-btn').forEach(b=>b.onclick=()=>{captureCurrentDoc();currentDoc=b.dataset.doc;renderDocs()});$('schoolSelect').onchange=e=>selectSchool(e.target.value);$('parseBtn').onclick=parseRaw;$('demoBtn').onclick=demo;$('addClassBtn').onclick=()=>addRow();$('validateBtn').onclick=validateRows;$('addRuleBtn').onclick=()=>{rules.push({code:'MANUAL_'+Date.now(),name:'Ngoại lệ',source:'manual',manualQty:0,tuition:0,service:0,note:''});renderRules();calculate()};$('addAdjustBtn').onclick=()=>{adjustments.push({sign:-1,text:'Giảm trừ khác',amount:0,commission:false});renderAdjustments();calculate()};$('saveBtn').onclick=saveCase;$('loadBtn').onclick=loadLastCase;$('resetBtn').onclick=resetCase;$('printAllBtn').onclick=printAll;$('downloadPdfBtn').onclick=printAll;$('regenerateDocBtn').onclick=regenerateCurrentDoc;$('excludeCurrentDocBtn').onclick=excludeCurrentDoc;$('exportWordBtn').onclick=exportWord;$('exportBackupBtn').onclick=exportBackup;$('importBackupInput').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);
 document.body.addEventListener('input',e=>{const r=e.target.dataset.r,k=e.target.dataset.k,rule=e.target.dataset.rule,adj=e.target.dataset.adj;if(r!==undefined){rows[+r][k]=['size','full','half','absent','teacherHalf'].includes(k)?(+e.target.value||0):e.target.value;docDrafts={};calculate()}if(rule!==undefined){rules[+rule][k]=['tuition','service','manualQty'].includes(k)?(+e.target.value||0):e.target.value;docDrafts={};renderRules();calculate()}if(adj!==undefined){adjustments[+adj][k]=k==='commission'?e.target.checked:(k==='amount'?+e.target.value||0:(k==='sign'?+e.target.value:e.target.value));docDrafts={};calculate()}if(['billMonth','docDate','repName','serviceName','showBank','companyAddress','bankAccount','bankName','commissionMode','commissionPct','commissionFixed'].includes(e.target.id)){docDrafts={};calculate()}});
 document.body.addEventListener('click',e=>{if(e.target.dataset.delrow!==undefined){rows.splice(+e.target.dataset.delrow,1);docDrafts={};renderRows()}if(e.target.dataset.delrule!==undefined){rules.splice(+e.target.dataset.delrule,1);docDrafts={};renderRules();calculate()}if(e.target.dataset.deladj!==undefined){adjustments.splice(+e.target.dataset.deladj,1);docDrafts={};renderAdjustments();calculate()}});
 $('docChecklist').addEventListener('change',e=>{const k=e.target.dataset.includeDoc;if(k){includedDocs[k]=e.target.checked;renderAllDocs();renderDocs();updateFilename()}})
}
function init(){bind();$('billMonth').value=currentMonth();$('docDate').value=isoToday();renderSchoolOptions();renderRows();renderRules();renderAdjustments();renderChecklist();calculate();renderDocs();loadBackend()}
init();